[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "nicopal"
version = "0.7.5"
description = "Nicopal: colour palettes designed for everyone."
readme = {file = "README.md", content-type = "text/markdown"}
authors = [{name = "Nicolas Tharaud", email="n.tharaud6@gmail.com"}]
license = {file="LICENSE"}
keywords = ["color", "palettes", "accessibility", "scientific", "color-deficiency"]
dependencies = ["matplotlib", "numpy"]

[project.optional-dependencies]
advanced = ["scipy", "cartopy"]

[tool.setuptools.package-data]
nicopal = ["data/*", "fonts/*"]

[project.urls]
Homepage = "https://github.com/nicolastharaud"